### YamlMime:Lifecycle
metadata:
  title: Program Microsoft Center Configuration Manager 2007 R3
  description: Program Microsoft System Center Configuration Manager 2007 R3 jest zgodny z zasadami stałego cyklu życia.
  ms.date: 07/28/2020
  ms.openlocfilehash: 1066e1999c057459643c64aba46bb88e34bb4842
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4137432"
name: Program Microsoft Center Configuration Manager 2007 R3
summary: >
  Program Microsoft System Center Configuration Manager 2007 R3 jest zgodny z zasadami [stałego](/lifecycle/policies/fixed) cyklu życia.



  > [!IMPORTANT]

  > Wsparcie dla tego produktu dobiegło końca. Zapoznaj się ze wskazówkami dotyczącymi migracji poniżej.
products:
- msc
policyType: fixed
supportDates:
  start: 2010-12-19T00:00:00.000-08:00
  end: 2014-07-08T22:59:59.999-08:00
  extendedEnd: 2019-07-09T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2010-12-19T00:00:00.000-08:00
  endDate: 2019-07-09T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Linki \n* [Wskazówki dotyczące migracji](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [Dodatkowe wytyczne dotyczące migracji](/mem/configmgr/core/migration/planning-for-migration)"
