### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 4.6
  description: Program Microsoft Application Virtualization 4.6 jest zgodny z zasadami stałego cyklu życia.
  ms.date: 09/01/2020
  keywords: for Remote Desktop Services,for Windows Desktops,Sequencer
  ms.openlocfilehash: e7ee52090b6e77209d2cc75b5862c21dfe4fe3dd
  ms.sourcegitcommit: af46dd09ccdabd80dcc49d2cd930cefa0b1ab8a6
  ms.translationtype: HT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 09/01/2020
  ms.locfileid: "935571"
name: Microsoft Application Virtualization 4.6
summary: >+
  Program Microsoft Application Virtualization 4.6 jest zgodny z zasadami [stałego](/lifecycle/policies/fixed) cyklu życia.


  Dotyczy to następujących edycji: for Remote Desktop Services, for Windows Desktops, Sequencer

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Linki \n* [Informacje o produktach i migracji](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Wskazówki dotyczące migracji](https://techcommunity.microsoft.com/t5/Product-Life-Cycle/FAST-products-approaching-the-end-of-extended-support-in-2018/td-p/101710)\n* [Polityka dodatku Service Pack](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Ponieważ klient App-V 4.6 korzysta z serwera App-V 4.5, serwer App-V 4.5 będzie nadal obsługiwany zgodnie z datami cyklu życia aplikacji App-V 4.6, gdy jest używany z obsługiwanym klientem App-V 4.6.\n\n## <a name=\"editions\"></a>Edycje \n* for Remote Desktop Services\n* for Windows Desktops\n* Sequencer"
