### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 for Windows Desktops
  description: Program Microsoft Application Virtualization Hosting 5.1 for Windows Desktops jest zgodny z zasadami stałego cyklu życia.
  ms.date: 09/10/2020
  keywords: for Windows Desktops
name: Microsoft Application Virtualization Hosting 5.1 for Windows Desktops
summary: |+
  Program Microsoft Application Virtualization Hosting 5.1 for Windows Desktops jest zgodny z zasadami [stałego](/lifecycle/policies/fixed) cyklu życia.

  Dotyczy to następujących edycji: for Windows Desktops

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Original Release
    startDate: 11/01/2015
    endDate: 04/14/2026
content: |

  ## <a name="links"></a>Linki 
  * [Informacje o produkcie](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)


  ## <a name="editions"></a>Edycje 
  * for Windows Desktops