### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center 2012 R2 Configuration Manager
  description: Program Microsoft System Center 2012 R2 Configuration Manager jest zgodny z zasadami stałego cyklu życia.
  ms.date: 03/12/2021
  keywords: 
  ms.openlocfilehash: b9a1c0fa5804c5929f39f72816e86e49c739d281
  ms.sourcegitcommit: 8465b0fa45ee2c451d1f1eaf7be9a1544cdad17f
  ms.translationtype: HT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 03/12/2021
  ms.locfileid: "1462917"
name: Microsoft System Center 2012 R2 Configuration Manager
summary: >+
  Program Microsoft System Center 2012 R2 Configuration Manager jest zgodny z zasadami [stałego](/lifecycle/policies/fixed) cyklu życia.


products:
- msc
policyType: fixed
supportDates:
  start: 01/16/2014
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
- version: Service Pack 1
  startDate: 05/12/2015
  endDate: 07/12/2022
- version: Original Release
  startDate: 01/16/2014
  endDate: 07/12/2016
content: "\n## <a name=\"links\"></a>Linki \n* [Polityka dodatku Service Pack](/lifecycle/policies/fixed#service-packs)\n* [Dokumentacja programu Configuration Manager](/mem/configmgr/core/misc/online-documentation)\n* [Wskazówki dotyczące migracji](https://techcommunity.microsoft.com/t5/configuration-manager-blog/system-center-2012-configuration-manager-is-approaching-end-of/ba-p/1650899)"
