### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center 2012 Configuration Manager
  description: Program Microsoft System Center 2012 Configuration Manager jest zgodny z zasadami stałego cyklu życia.
  ms.date: 03/12/2021
  keywords: null
name: Microsoft System Center 2012 Configuration Manager
summary: |+
  Program Microsoft System Center 2012 Configuration Manager jest zgodny z zasadami [stałego](/lifecycle/policies/fixed) cyklu życia.


products:
  - msc
policyType: fixed
supportDates:
  start: 05/30/2012
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
  - version: Service Pack 2
    startDate: 05/12/2015
    endDate: 07/12/2022
  - version: Service Pack 1
    startDate: 12/15/2012
    endDate: 07/12/2016
  - version: Original Release
    startDate: 05/30/2012
    endDate: 01/14/2014
content: |+

  ## <a name="links"></a>Linki 
  * [Polityka dodatku Service Pack](/lifecycle/policies/fixed#service-packs)
  * [Dokumentacja System Center](/system-center/#pivot=components&panel=components-all)
  * [System Center Resources](https://www.microsoft.com/system-center/resources)
  * [Wskazówki dotyczące migracji](https://techcommunity.microsoft.com/t5/configuration-manager-blog/system-center-2012-configuration-manager-is-approaching-end-of/ba-p/1650899)