### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 5.1
  description: Program Microsoft Application Virtualization 5.1 jest zgodny z zasadami stałego cyklu życia.
  ms.date: 09/10/2020
  keywords: for Remote Desktop Services,for Windows Desktops
  ms.openlocfilehash: 5ebb28c8965d47f928547b36980e68ed6cc9c791
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4155710"
name: Microsoft Application Virtualization 5.1
summary: >+
  Program Microsoft Application Virtualization 5.1 jest zgodny z zasadami [stałego](/lifecycle/policies/fixed) cyklu życia.


  Dotyczy to następujących edycji: for Remote Desktop Services, for Windows Desktops

products:
- windows
policyType: fixed
supportDates:
  start: 2015-11-01T00:00:00.000-08:00
  end: 2018-01-09T22:59:59.999-08:00
  extendedEnd: 2026-04-14T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2015-11-01T00:00:00.000-08:00
  endDate: 2026-04-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Linki \n* [Informacje o produkcie](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)\n\n\n## <a name=\"editions\"></a>Edycje \n* for Remote Desktop Services\n* for Windows Desktops"
