### YamlMime:Lifecycle
metadata:
  title: Program Microsoft System Center 2012 R2 — menedżer konfiguracji
  description: Program Microsoft System Center 2012 R2 Configuration Manager jest zgodny z zasadami stałego cyklu życia.
  ms.date: 07/28/2020
  ms.openlocfilehash: 61515e636a9af310a2107c9505067fa551d26b15
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "859878"
name: Program Microsoft System Center 2012 R2 — menedżer konfiguracji
summary: >+
  Program Microsoft System Center 2012 R2 Configuration Manager jest zgodny z zasadami [stałego](/lifecycle/policies/fixed) cyklu życia.


products:
- msc
policyType: fixed
supportDates:
  start: 01/16/2014
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
- version: Service Pack 1
  startDate: 05/12/2015
  endDate: 07/12/2022
- version: Original Release
  startDate: 01/16/2014
  endDate: 07/12/2016
content: "\n## <a name=\"links\"></a>Linki \n* [Zasady dodatku Service Pack](/lifecycle/policies/fixed#service-packs)\n* [Dokumentacja programu Configuration Manager](/mem/configmgr/core/misc/online-documentation)"
