### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.6 for Windows Desktops
  description: Program Microsoft Application Virtualization Hosting 4.6 for Windows Desktops jest zgodny z zasadami stałego cyklu życia.
  ms.date: 07/28/2020
  ms.openlocfilehash: 21ed557cd6333e43a274796a3b25791c0d7f96cd
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: HT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "832236"
name: Microsoft Application Virtualization Hosting 4.6 for Windows Desktops
summary: >+
  Program Microsoft Application Virtualization Hosting 4.6 for Windows Desktops jest zgodny z zasadami [stałego](/lifecycle/policies/fixed) cyklu życia.


  Dotyczy to następujących edycji: for Windows Desktops

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Linki \n* [Informacje o produktach i migracji](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Polityka dodatku Service Pack](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Ponieważ klient App-V 4.6 korzysta z serwera App-V 4.5, serwer App-V 4.5 będzie nadal obsługiwany zgodnie z datami cyklu życia aplikacji App-V 4.6, gdy jest używany z obsługiwanym klientem App-V 4.6.\n\n## <a name=\"editions\"></a>Edycje \n* for Windows Desktops"
