### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager (LTSB — wersja 1606)
  description: Program Microsoft System Center Configuration Manager (LTSB — wersja 1606) jest zgodny z zasadami stałego cyklu życia.
  ms.date: 08/20/2020
  ms.openlocfilehash: 6475679aee15c8748a0fc3092509dee7010472d848ac73e54be2c605a19595e5
  ms.sourcegitcommit: 1c28c95e7a2b743cff45216da63f72ffbad026ed
  ms.translationtype: HT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 08/06/2021
  ms.locfileid: "2511251"
name: Microsoft System Center Configuration Manager (LTSB — wersja 1606)
summary: >+
  Program Microsoft System Center Configuration Manager (LTSB — wersja 1606) jest zgodny z zasadami [stałego](/lifecycle/policies/fixed) cyklu życia.


products:
- m365
policyType: fixed
supportDates:
  start: 10/12/2016
  end: 10/12/2021
  extendedEnd: 01/12/2027
releases:
- version: Original Release
  startDate: 10/12/2016
  endDate: 01/12/2027
content: "\n## <a name=\"links\"></a>Linki \n* [Informacje dotyczące obsługi i pomocy technicznej](/sccm/core/understand/learn-more-editions)"
