### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R2
  description: Program Microsoft System Center Configuration Manager 2007 R2 jest zgodny z zasadami stałego cyklu życia.
  ms.date: 07/28/2020
  ms.openlocfilehash: 0da71b9a2886e1a7012339ebef9a5fbe64f8811e
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: HT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "832118"
name: Microsoft System Center Configuration Manager 2007 R2
summary: >
  Program Microsoft System Center Configuration Manager 2007 R2 jest zgodny z zasadami [stałego](/lifecycle/policies/fixed) cyklu życia.



  > [!IMPORTANT]

  > Wsparcie dla tego produktu dobiegło końca. Zapoznaj się ze wskazówkami dotyczącymi migracji poniżej.
products:
- msc
policyType: fixed
supportDates:
  start: 11/29/2008
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 11/29/2008
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>Linki \n* [Wskazówki dotyczące migracji](/mem/configmgr/core/migration/planning-for-migration)\n* [Dodatkowe wytyczne dotyczące migracji](/mem/configmgr/core/migration/migrate-data-between-hierarchies)"
