### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Program Microsoft Forefront Client Security jest zgodny ze stałymi zasadami cyklu życia.
  ms.date: 08/21/2020
  ms.openlocfilehash: 802c6836324ac39b0b8ffc99c1f7f6734906445b
  ms.sourcegitcommit: 2f3e18a9447115504ef274bd044dbcdb08231f5b
  ms.translationtype: MT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 08/25/2020
  ms.locfileid: "908850"
name: Microsoft Forefront Client Security
summary: >+
  Program Microsoft Forefront Client Security jest zgodny ze [stałymi](/lifecycle/policies/fixed) zasadami cyklu życia.


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Linki \n* [Program System Center Endpoint Protection](http://www.microsoft.com/server-cloud/products/system-center-2012-r2-configuration-manager/default.aspx)\n\n> [!NOTE]\n> Usługa Forefront Client Security została wycofana. Pomoc techniczna kończy się 14 lipca 2015 r. Aktualizacje definicji przed złośliwym oprogramowaniem i programem Antyszpiegowskim nie będą już dostępne po zakończeniu obsługi wersji produktu. Wypróbuj program System Center Endpoint Protection jako zamiennik."
