### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R2
  description: Program Microsoft System Center Configuration Manager 2007 R2 jest zgodny z zasadami stałego cyklu życia.
  ms.date: 07/28/2020
  ms.openlocfilehash: d74ead7a94de9a66a4f34abab6d8ff9b4496c86479bf1242d36b903855a6e66f
  ms.sourcegitcommit: 1c28c95e7a2b743cff45216da63f72ffbad026ed
  ms.translationtype: HT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 08/06/2021
  ms.locfileid: "2511288"
name: Microsoft System Center Configuration Manager 2007 R2
summary: >
  Program Microsoft System Center Configuration Manager 2007 R2 jest zgodny z zasadami [stałego](/lifecycle/policies/fixed) cyklu życia.



  > [!IMPORTANT]

  > Wsparcie dla tego produktu dobiegło końca. Zapoznaj się ze wskazówkami dotyczącymi migracji poniżej.
products:
- msc
policyType: fixed
supportDates:
  start: 11/29/2008
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 11/29/2008
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>Linki \n* [Wskazówki dotyczące migracji](/mem/configmgr/core/migration/planning-for-migration)\n* [Dodatkowe wytyczne dotyczące migracji](/mem/configmgr/core/migration/migrate-data-between-hierarchies)"
