### YamlMime:Lifecycle
metadata:
  title: Wirtualizacja aplikacji firmy Microsoft 5.1
  description: Wirtualizacja aplikacji firmy Microsoft 5.1 jest zgodna z zasadami stałego cyklu życia.
  ms.date: 07/28/2020
  ms.openlocfilehash: 3f0cac2ee013dd73e44fe41d9ba1d07cfcfce2f1
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "859926"
name: Wirtualizacja aplikacji firmy Microsoft 5.1
summary: >+
  Wirtualizacja aplikacji firmy Microsoft 5.1 jest zgodna z zasadami [stałego](/lifecycle/policies/fixed) cyklu życia.


  Dotyczy to następujących wersji: dla usług pulpitu zdalnego dla pulpitów systemu Windows

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Linki \n* [Informacje o produkcie](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)\n\n\n## <a name=\"editions\"></a>Wersje \n* dla usług pulpitu zdalnego\n* dla komputerów z systemem Windows Desktops"
