### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 5.1
  description: Program Microsoft Application Virtualization 5.1 jest zgodny z zasadami stałego cyklu życia.
  ms.date: 09/10/2020
  keywords: 'for Remote Desktop Services,for Windows Desktops'
name: Microsoft Application Virtualization 5.1
summary: |+
  Program Microsoft Application Virtualization 5.1 jest zgodny z zasadami [stałego](/lifecycle/policies/fixed) cyklu życia.

  Dotyczy to następujących edycji: for Remote Desktop Services, for Windows Desktops

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Original Release
    startDate: 11/01/2015
    endDate: 04/14/2026
content: |

  ## <a name="links"></a>Linki 
  * [Informacje o produkcie](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)


  ## <a name="editions"></a>Edycje 
  * for Remote Desktop Services
  * for Windows Desktops