### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.0 for Windows Desktops
  description: Program Microsoft Application Virtualization Hosting 5.0 for Windows Desktops jest zgodny z zasadami stałego cyklu życia.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 47a19d53aa66987491ba097905f0388269c66ff0
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4146386"
name: Microsoft Application Virtualization Hosting 5.0 for Windows Desktops
summary: >+
  Program Microsoft Application Virtualization Hosting 5.0 for Windows Desktops jest zgodny z zasadami [stałego](/lifecycle/policies/fixed) cyklu życia.


  Dotyczy to następujących edycji: for Windows Desktops

products:
- windows
policyType: fixed
supportDates:
  start: 2012-11-01T00:00:00.000-08:00
  end: 2018-01-09T22:59:59.999-08:00
  extendedEnd: 2026-04-14T22:59:59.999-08:00
releases:
- version: Service Pack 3
  startDate: 2014-12-08T00:00:00.000-08:00
  endDate: 2026-04-14T22:59:59.999-08:00
- version: Service Pack 2
  startDate: 2013-11-08T00:00:00.000-08:00
  endDate: 2016-01-12T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2013-04-10T00:00:00.000-08:00
  endDate: 2015-01-13T22:59:59.999-08:00
- version: Original Release
  startDate: 2012-11-01T00:00:00.000-08:00
  endDate: 2014-07-08T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Linki \n* [Informacje o produkcie](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Polityka dodatku Service Pack](/lifecycle/policies/fixed#service-packs)\n\n\n## <a name=\"editions\"></a>Edycje \n* for Windows Desktops"
