### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007
  description: Program Microsoft System Center Configuration Manager 2007 jest zgodny z zasadami stałego cyklu życia.
  ms.date: 07/28/2020
name: Microsoft System Center Configuration Manager 2007
summary: |
  Program Microsoft System Center Configuration Manager 2007 jest zgodny z zasadami [stałego](/lifecycle/policies/fixed) cyklu życia.


  > [!IMPORTANT]
  > Wsparcie dla tego produktu dobiegło końca. Zapoznaj się ze wskazówkami dotyczącymi migracji poniżej.
products:
  - msc
policyType: fixed
supportDates:
  start: 11/29/2007
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
  - version: Service Pack 2
    startDate: 10/22/2009
    endDate: 07/09/2019
  - version: Service Pack 1
    startDate: 05/21/2008
    endDate: 01/11/2011
  - version: Original Release
    startDate: 11/29/2007
    endDate: 07/14/2009
content: |+

  ## <a name="links"></a>Linki 
  * [Wskazówki dotyczące migracji](/mem/configmgr/core/migration/migrate-data-between-hierarchies)
  * [Informacje o produkcie](/mem/configmgr/core/understand/introduction)
  * [Polityka dodatku Service Pack](/lifecycle/policies/fixed#service-packs)