### YamlMime:Lifecycle
metadata:
  title: Pakiet PixelSense Applications Suite 1.0
  description: Pakiet PixelSense Applications Suite 1.0 jest zgodny z zasadami stałego cyklu życia.
  ms.date: 08/12/2020
  ms.openlocfilehash: 6fd336d656015cb5896b7c4c5b0081db19eeddcc80bff037c3f583644d996d3a
  ms.sourcegitcommit: 1c28c95e7a2b743cff45216da63f72ffbad026ed
  ms.translationtype: HT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 08/06/2021
  ms.locfileid: "2502074"
name: Pakiet PixelSense Applications Suite 1.0
summary: >+
  Pakiet PixelSense Applications Suite 1.0 jest zgodny z zasadami [stałego](/lifecycle/policies/fixed) cyklu życia.


products:
- windows
policyType: fixed
supportDates:
  start: 01/01/2009
  end: 01/14/2014
  extendedEnd: 01/08/2019
releases:
- version: Service Pack 1
  startDate: 08/09/2009
  endDate: 01/08/2019
- version: Original Release
  startDate: 01/01/2009
  endDate: 01/08/2019
content: ''
