### YamlMime:Lifecycle
metadata:
  title: Brama aplikacji Whale Communications Intelligent Application Gateway
  description: Brama Application Whale jest zgodna ze stałymi zasadami cyklu życia.
  ms.date: 08/21/2020
  ms.openlocfilehash: 4946cfbd0c53706853138bd707157a5c318b8dc6
  ms.sourcegitcommit: bc7fcda30191f92db77ed2e7f74d5816ac276a55
  ms.translationtype: MT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 08/21/2020
  ms.locfileid: "907151"
name: Brama aplikacji Whale Communications Intelligent Application Gateway
summary: >+
  Brama Application Whale jest zgodna ze [stałymi](/lifecycle/policies/fixed) zasadami cyklu życia.


products:
- windows
policyType: fixed-mainstream-only
supportDates:
  start: 10/10/2007
  end: 07/13/2010
releases:
- version: "3.1"
  startDate: 10/10/2007
  endDate: 07/08/2008
- version: "3.6"
  startDate: 10/10/2007
  endDate: 07/13/2010
content: "\n\n> [!NOTE]\n> Pomoc techniczna dotycząca tego produktu podlega warunkom jego nabycia."
